// frontend-vue/src/views/DashBoard.vue

<template>
    <main>
        <div class="container">
            <div class="row pt-4 justify-content-around">
                <div class="col-md-5 d-flex justify-content-around shadow p-3 mb-5 bg-body-tertiary rounded">
                    <Bar id="my-chart-id" :options="chartOptions" :data="chartData" />

                </div>
                <div class="col-md-5 d-flex justify-content-around shadow p-3 mb-5 bg-body-tertiary rounded">
                    <Bubble id="my-chart-id" :options="chartOptions" :data="datasetsB"></Bubble>
                </div>
            </div>
            <div class="row pt-4 d-flex justify-content-around">
                <div class="col-md-5 d-flex justify-content-around shadow p-3 mb-5 bg-body-tertiary rounded ">
                    <Radar  id="my-chart-id" :options="chartOptions" :data="datasetA" ></Radar>
                </div>
            </div>
        </div>
    </main>
</template>
<script>
import { Bar, Bubble, Radar } from 'vue-chartjs'
import { Chart as ChartJS, Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, PointElement, RadialLinearScale, LineElement, Filler, } from 'chart.js'

ChartJS.register(Title, Tooltip, Legend, BarElement, CategoryScale, LinearScale, PointElement, RadialLinearScale, LineElement, Filler,)

export default {
    name: 'BarChart',
    components: { Bar, Bubble,Radar },
    data() {
        return {
            chartData: {
                labels: ['January', 'February', 'March'],
                datasets: [{
                    data: [40, 20, 12], backgroundColor: ["rgba(255, 99, 132, 0.5)", "rgba(54, 162, 235, 0.5)", "rgba(75, 192, 192, 0.5)"],
                    borderColor: "#36495d"
                }]
            },
            chartOptions: {
                responsive: true
            },
            datasetsB: {

                label: 'Data One',
                datasets: [{
                    backgroundColor: '#f87979',
                    data: [
                        {
                            x: 20,
                            y: 25,
                            r: 5
                        },
                        {
                            x: 40,
                            y: 10,
                            r: 10
                        },
                        {
                            x: 30,
                            y: 22,
                            r: 30
                        }
                    ]
                }]
                ,

            },
            datasetA: {
                labels: [
                    'Eating',
                    'Drinking',
                    'Sleeping',
                    'Designing',
                    'Coding',
                    'Cycling',
                    'Running'
                ],
                datasets: [
                    {
                        label: 'My First dataset',
                        backgroundColor: 'rgba(179,181,198,0.2)',
                        borderColor: 'rgba(179,181,198,1)',
                        pointBackgroundColor: 'rgba(179,181,198,1)',
                        pointBorderColor: '#fff',
                        pointHoverBackgroundColor: '#fff',
                        pointHoverBorderColor: 'rgba(179,181,198,1)',
                        data: [65, 59, 90, 81, 56, 55, 40]
                    },
                    {
                        label: 'My Second dataset',
                        backgroundColor: 'rgba(255,99,132,0.2)',
                        borderColor: 'rgba(255,99,132,1)',
                        pointBackgroundColor: 'rgba(255,99,132,1)',
                        pointBorderColor: '#fff',
                        pointHoverBackgroundColor: '#fff',
                        pointHoverBorderColor: 'rgba(255,99,132,1)',
                        data: [28, 48, 40, 19, 96, 27, 100]
                    }
                ]
            }
        }
    }
}
</script>

// frontend-angular/src/app/paginas/dashboard/dashboard.component.ts
import { Component } from '@angular/core';
import { ChartConfiguration, ChartOptions } from "chart.js";
@Component({
  selector: 'app-dashboard',
  templateUrl: './dashboard.component.html',
})
export class DashboardComponent {
  public chart: any;

  ngOnInit(): void {

  }
  title = 'ng2-charts-demo';

  public lineChartData: ChartConfiguration<'line'>['data'] = {
    labels: [
      'January',
      'February',
      'March',
      'April',
      'May',
      'June',
      'July'
    ],
    datasets: [
      {
        data: [65, 59, 80, 81, 56, 55, 40],
        label: 'Series A',
        fill: true,
        tension: 0.5,
        borderColor: 'black',
        backgroundColor: 'rgba(255,0,0,0.3)'
      }
    ]
  };
  public lineChartOptions: ChartOptions<'line'> = {
    responsive: false
  };
  public lineChartLegend = true;
 

  public barChartLegend = true;
  public barChartPlugins = [];

  public barChartData: ChartConfiguration<'bar'>['data'] = {
    labels: [ '2006', '2007', '2008', '2009', '2010', '2011', '2012' ],
    datasets: [
      { data: [ 65, 59, 80, 81, 56, 55, 40 ], label: 'Series A' },
      { data: [ 28, 48, 40, 19, 86, 27, 90 ], label: 'Series B' }
    ]
  };

  public barChartOptions: ChartConfiguration<'bar'>['options'] = {
    responsive: false,
  };
  public pieChartOptions: ChartOptions<'pie'> = {
    responsive: false,
  };
  public pieChartLabels = [ [ 'Download', 'Sales' ], [ 'In', 'Store', 'Sales' ], 'Mail Sales' ];
  public pieChartDatasets = [ {
    data: [ 300, 500, 100 ]
  } ];
  public pieChartLegend = true;
  public pieChartPlugins = [];

}

<div class="container">
    <div class="row pt-4 justify-content-around">
        <div class="col-md-5 d-flex justify-content-around shadow p-3 mb-5 bg-body-tertiary rounded">
            <canvas baseChart width="400" height="400" [type]="'line'" [data]="lineChartData"
                [options]="lineChartOptions" [legend]="lineChartLegend">
            </canvas>
        </div>
        <div class="col-md-5 d-flex justify-content-around shadow p-3 mb-5 bg-body-tertiary rounded">
            <canvas baseChart width="400" height="400" [type]="'pie'" [datasets]="pieChartDatasets"
                [labels]="pieChartLabels" [options]="pieChartOptions" [plugins]="pieChartPlugins"
                [legend]="pieChartLegend">
            </canvas>
        </div>
    </div>
    <div class="row pt-4 d-flex justify-content-around">
        <div class="col-md-5 d-flex justify-content-around shadow p-3 mb-5 bg-body-tertiary rounded ">
            <canvas baseChart width="400" height="400" [data]="barChartData" [options]="barChartOptions"
                [plugins]="barChartPlugins" [legend]="barChartLegend" [type]="'bar'">
            </canvas>
        </div>
    </div>
</div>
